import './js/authFireBase.js';
import './js/dark-mode';
// import { spinnerStart, spinnerStop } from './js/loader';
import './js/footer-modal';
import './js/trending-search-main/trending-search.js';
import './js/movie_modal';
import './js/openModalWindow.js';
import './js/scroll_to_top';
import './js/movie-search/search-by-keyword';
import './js/movie-search/search-by-year';
import './js/movie-search/search-by-genre';
import './js/movie-search/advanced-search';
