import './js/authFireBaseLibrary.js';
import './js/openModalWindow.js';
import './js/my-library-watched-queue/my-library-watched-queue';
import './js/dark-mode';
import './js/footer-modal';
import { spinnerStart, spinnerStop } from './js/loader';
spinnerStart();
setTimeout(spinnerStop, 3000);
import './js/scroll_to_top';
import './js/movie_modal-library.js';
import './js/openModalWindow.js';
